# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eba2d7a949cca04734c72abb715797c1b91debc297792414bf3c13d0da3785e6dae860eb144e45c9d7a3d33d3dd27cb1a957f8d4155f01fe1fe796f6920003c

test:
  secret_key_base: 040a3ba6dad24783d1934ac018b62517a0a27e2152e1893d16136b0d943f7b9957dabcd43e3d50fe7aea8e7dca053b1c656b645976fc32233c06cc8e96c52893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
